# Workflow Configuration

# CI/CD Settings
ci:
  python_version: "3.8"
  test_coverage_threshold: 80
  code_quality_threshold: 90
  security_scan_threshold: 95

# Release Management
release:
  version_pattern: "^v[0-9]+\\.[0-9]+\\.[0-9]+$"
  changelog_path: "CHANGELOG.md"
  release_branches:
    - "main"
    - "develop"

# Dependency Management
dependencies:
  update_schedule: "0 0 * * 0"  # Weekly updates
  excluded_packages:
    - "tensorflow"
    - "torch"
  security_scan: true

# Code Quality
code_quality:
  tools:
    - "black"
    - "flake8"
    - "mypy"
    - "bandit"
  thresholds:
    complexity: 10
    maintainability: 80
    test_coverage: 80

# AI Model Management
ai_models:
  validation_thresholds:
    accuracy: 0.95
    bias: 0.1
    fairness: 0.9
  monitoring:
    drift_threshold: 0.05
    performance_threshold: 0.9
  storage:
    artifacts_path: "models/artifacts"
    model_cards_path: "docs/model_cards"

# Data Management
data:
  quality_thresholds:
    completeness: 0.95
    accuracy: 0.9
    consistency: 0.95
  storage:
    artifacts_path: "data/artifacts"
    validation_path: "data/validation"

# Security & Compliance
security:
  scan_schedule: "0 0 * * 0"  # Weekly scans
  compliance_standards:
    - "GDPR"
    - "CCPA"
  vulnerability_threshold: "high"

# Testing
testing:
  smoke_tests_path: "tests/smoke_tests"
  load_tests_path: "tests/load_tests"
  performance_thresholds:
    response_time: 200  # ms
    throughput: 1000    # requests/second
    error_rate: 0.01    # 1%

# Documentation
documentation:
  build_command: "mkdocs build"
  output_path: "site"
  auto_update: true

# Monitoring
monitoring:
  alert_thresholds:
    cpu_usage: 80
    memory_usage: 80
    disk_usage: 80
  metrics:
    - "response_time"
    - "error_rate"
    - "throughput"
    - "model_performance"
    - "data_quality" 