site_name: Amega AI
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - About: about.md
  - API Documentation: api.md
  - Guides:
    - Getting Started: guides/getting-started.md
    - Installation: guides/installation.md
    - Configuration: guides/configuration.md
  - Development:
    - Contributing: development/contributing.md
    - Code Style: development/code-style.md
    - Testing: development/testing.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - toc:
      permalink: true
  - attr_list
  - def_list
  - tables
  - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nkwenti-severian-ndongtsop/amega-ai
    - icon: fontawesome/brands/discord
      link: https://discord.gg/amega-ai 