# Amega AI Configuration Example

# Basic Settings
app:
  name: Amega AI
  environment: development  # development, staging, production, testing
  version: 0.1.0

# API Settings
api:
  host: 0.0.0.0
  port: 8000
  debug: false
  root_path: ""
  docs_url: /docs
  openapi_url: /openapi.json

# Database Settings
database:
  url: postgresql://user:password@localhost:5432/amega_ai
  pool_size: 5
  max_overflow: 10
  echo: false

# Security Settings
security:
  jwt_secret_key: your-secret-key-here
  jwt_algorithm: HS256
  access_token_expire_minutes: 30
  cors_origins:
    - http://localhost
    - http://localhost:3000
  ssl_keyfile: null
  ssl_certfile: null

# LLM Settings
llm:
  backend: ollama  # ollama, openai, anthropic
  api_key: null
  api_url: null
  default_model: llama2
  max_tokens: 1000
  temperature: 0.7

# Logging Settings
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: logs/amega.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  max_bytes: 10485760  # 10MB
  backup_count: 5

# Redis Settings
redis:
  url: redis://localhost:6379
  password: null
  ssl: false
  ssl_cert_reqs: null

# Directory Settings
directories:
  models: models
  data: data
  cache: cache 