name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort mypy pylint bandit

      - name: Run Black
        run: black . --check

      - name: Run isort
        run: isort . --check-only

      - name: Run mypy
        run: mypy .

      - name: Run pylint
        run: pylint **/*.py

      - name: Run bandit
        run: bandit -r .

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Build documentation
        run: mkdocs build --strict

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --no-progress --format detailed 