name: Data Management

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'data/**'
      - 'datasets/**'
  schedule:
    - cron: '0 0 * * 0'  # Weekly data checks
  workflow_dispatch:

jobs:
  data-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy great-expectations

      - name: Validate data quality
        run: |
          python scripts/validate_data_quality.py

      - name: Check data completeness
        run: |
          python scripts/check_data_completeness.py

      - name: Generate data quality report
        run: |
          python scripts/generate_data_quality_report.py

  data-privacy:
    needs: data-quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check for sensitive data
        run: |
          python scripts/check_sensitive_data.py

      - name: Anonymize data
        run: |
          python scripts/anonymize_data.py

      - name: Validate privacy compliance
        run: |
          python scripts/validate_privacy_compliance.py

  data-versioning:
    needs: data-privacy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Version datasets
        run: |
          python scripts/version_datasets.py

      - name: Update data registry
        run: |
          python scripts/update_data_registry.py

      - name: Store data artifacts
        uses: actions/upload-artifact@v3
        with:
          name: data-artifacts
          path: data/artifacts/

  data-documentation:
    needs: data-versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate data documentation
        run: |
          python scripts/generate_data_documentation.py

      - name: Update data catalog
        run: |
          python scripts/update_data_catalog.py 