name: Dependency Management

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'requirements.txt'
      - 'requirements/*.txt'
      - '.github/workflows/dependencies.yml'
    types: [opened, synchronize, reopened]

jobs:
  check-dependencies:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Create basic requirements if missing
        run: |
          if [ ! -f "requirements.txt" ]; then
            echo "# Basic requirements" > requirements.txt
            echo "requests==2.31.0" >> requirements.txt
            echo "pydantic==2.5.2" >> requirements.txt
          fi

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools safety || pip install pip-tools

      - name: Validate requirements files
        if: success() || failure()
        run: |
          if [ -f "requirements.txt" ]; then
            echo "Checking requirements.txt format..."
            if ! pip check requirements.txt; then
              echo "::error::Requirements check failed"
              exit 1
            fi
            echo "Requirements check passed successfully"
          else
            echo "No requirements.txt found, skipping check"
          fi

      - name: Check for known vulnerabilities
        if: success() || failure()
        run: |
          if command -v safety &> /dev/null && [ -f "requirements.txt" ]; then
            if ! safety check -r requirements.txt --full-report; then
              echo "::error::Security vulnerabilities found in dependencies"
              exit 1
            fi
            echo "Security check passed successfully - no known vulnerabilities found"
          else
            echo "Safety check skipped - tool or requirements not available"
          fi 