name: Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material==9.6.* mkdocs-material-extensions==1.3.*
          pip install mkdocs-git-revision-date-localized-plugin==1.2.* mkdocs-minify-plugin==0.8.*
          pip install mkdocs-glightbox==0.3.* mkdocs-git-authors-plugin==0.7.*
          pip install mkdocs-git-committers-plugin==0.2.* mkdocs-awesome-pages-plugin==2.9.*
          pip install mkdocs-redirects==1.2.* mkdocs-static-i18n==1.2.*

      - name: Create default mkdocs config
        run: |
          if [ ! -f "mkdocs.yml" ]; then
            echo "Creating default mkdocs.yml"
            cat > mkdocs.yml << 'EOF'
            site_name: Amega AI
            theme:
              name: material
              features:
                - navigation.tabs
                - navigation.sections
                - navigation.top
                - search.highlight
            markdown_extensions:
              - pymdownx.highlight:
                  anchor_linenums: true
              - pymdownx.inlinehilite
              - pymdownx.snippets
              - pymdownx.superfences
            nav:
              - Home: index.md
              - About: about.md
            EOF
          fi

      - name: Ensure docs structure
        run: |
          mkdir -p docs
          if [ ! -f "docs/index.md" ]; then
            echo "# Welcome to Amega AI" > docs/index.md
            echo "Documentation is under construction." >> docs/index.md
          fi
          if [ ! -f "docs/about.md" ]; then
            echo "# About Amega AI" > docs/about.md
            echo "More information coming soon." >> docs/about.md
          fi

      - name: Build documentation
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mkdocs gh-deploy --force

      - name: Generate build report
        if: always()
        run: |
          {
            echo "## Documentation Build Report"
            echo "### Status"
            echo "- Build: ${{ job.status }}"
            echo "### Files"
            echo '```'
            ls -R site/ 2>/dev/null || echo "No site directory found"
            echo '```'
          } > docs-report.md

      - name: Upload documentation artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: |
            site/
            docs-report.md
          retention-days: 5 
