name: AI Ethics and Compliance

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'models/**'
      - 'training/**'
      - 'data/**'
  schedule:
    - cron: '0 0 * * 0'  # Weekly ethics checks
  workflow_dispatch:

jobs:
  ethics-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aif360 fairlearn

      - name: Check for bias
        run: |
          python scripts/check_model_bias.py

      - name: Evaluate fairness
        run: |
          python scripts/evaluate_fairness.py

      - name: Check ethical guidelines
        run: |
          python scripts/check_ethical_guidelines.py

  compliance:
    needs: ethics-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Check GDPR compliance
        run: |
          python scripts/check_gdpr_compliance.py

      - name: Check CCPA compliance
        run: |
          python scripts/check_ccpa_compliance.py

      - name: Generate compliance report
        run: |
          python scripts/generate_compliance_report.py

  transparency:
    needs: compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate model cards
        run: |
          python scripts/generate_model_cards.py

      - name: Create transparency report
        run: |
          python scripts/create_transparency_report.py

      - name: Update documentation
        run: |
          python scripts/update_ethics_documentation.py

  alert:
    needs: transparency
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Create ethics issue
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Ethics Alert: ${{ github.workflow }} failed',
              body: 'The ethics and compliance check failed. Please review the logs.',
              labels: ['ethics', 'compliance', 'alert']
            }); 