name: Pull Request GPT Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    name: Code Review GPT
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL: "gpt-3.5-turbo"
          LANGUAGE: "en"
          REVIEW_COMMENT_PREFIX: "🤖 AI Review:"
          REVIEW_STYLE: "code-improvement"
          VERBOSE: true
